### PR TITLE
Von hamos beckhoff

### PR DESCRIPTION
**Pull request by jsheppard95**
## Description
- Added class `vonhamos_motion.VonHamos`. Currently, this just contains a single vertical axis, with the rest of the Von Hamos system using LCLS-I style dumb motors with MForce Chassis.
- Currently feels like overkill to have separate class for one Beckhoff axis, but eventually all LCLS-I dumb motors will be converted to Beckhoff axes and can be included in this class

## Motivation and Context
- Need to control Von Hamos Y axis. This originally was a dumb motor but it needed to be replaced. Thus, the decision was made to start the Beckhoff conversion with this single axis.

## How Has This Been Tested?
- Ran `pcdsdevices` test suite, no failed tests.
- Instantiated object in Ipython session/inspected components
- Opened test typhos screen

## Where Has This Been Documented?
- Docstrings

## Pre-merge checklist
- [X] Code works interactively
- [X] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [X] Test suite passes locally
- [ ] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by ZLLentz** [comment]
A bit confused here:
- Is it not good enough to just make a BeckhoffAxis in xpp's python?
- Is it not possible to include the other axes? There is an IMS class.

**Comment by klauer** [comment]
Makes sense to include the IMS axes and then change them over to Beckhoff if/when the hardware switchover happens.

**Comment by jsheppard95** [comment]
Yes I think you are both right. For the LV68 experiment, there's no reason I couldn't just add this axis to xpp3. I could even make a happi entry for it and set the class as `epics_motor.BeckhoffAxis` so we can have a simple typhos screen as well. And yes I should definitely have the other axes in here as well, and just set them as IMS for now.

**Comment by ZLLentz** [comment]
Ok, which direction do you want to go then?
1. fix travis style complaints and merge PR essentially as-is
2. table PR for now, get xpp working without
3. update PR to have all the axes

I'll be happy with any of these or another suggestion

**Comment by jsheppard95** [comment]
I ended up going with option 2 for now just to get to get XPP going. I just added the axis to `xpp3` and then made a happi entry for the motor itself with the name `hxx_von_hamos_y` and class `pcdsdevices.epics_motor.BeckhoffAxis`, just to have a simple GUI as well.

So tabling the PR for now, but it would be awesome to have a permanent class. I realized though its a bit tricky with some of the axes as IMS, since we run these through the MForce Chassis PPL's and thus the PVs change depending on which hutch/channels are chosen. So far its only Y that's fixed since its running on the Beckhoff panel. Does it make sense to specify the IMS PVs in the `__init__` for now?

**Comment by ZLLentz** [comment]
You can totally specify all the PVs in the ``__init__`` if you like- it's a bit annoying to do but we put some magic in with `UnrelatedComponent` to make it easier. See example usage here: https://github.com/pcdshub/pcdsdevices/blob/dc9237ce539da7de76bf31371652b9506ff3ef99/pcdsdevices/sample_delivery.py#L277-L400

This is probably the way to go if you want a permanent class with migrating IOCs, if you think that's a useful thing to have.

**Comment by ZLLentz** [comment]
I'm going to close this PR, assuming you have other things you'd prefer to be spending your time on @jsheppard95. Feel free to re-open if I was wrong.

**Comment by jsheppard95** [comment]
Yes closing this PR was appropriate, definitely other things I'd prefer to work on, but if a greater need arises I'll return/reopen.

**Pull request closed without merging**
