### PR TITLE
ENH: swap out cf-units for pint for portability

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

`cf-units` -> `pint`

## Motivation and Context

`cf-units` is not platform-independent because it relies on udunits being installed
`pint` is pure python

## How Has This Been Tested?

Tests still pass

### CODE REVIEW

**Comment by ZLLentz** [comment]
I'm going to use the codecov output to check

**Comment by ZLLentz** [comment]
```
In [2]: convert_unit(100, 'meters', 'centimeters')
Out[2]: 10000.0

In [3]: convert_unit(100, 'ns', 'sec')
Out[3]: 1.0000000000000001e-07
```

**Comment by ZLLentz** [comment]
Terminal coverage snippit since I remembered I can do that
```
Name                                    Stmts   Miss  Cover   Missing
---------------------------------------------------------------------
pcdsdevices/pseudopos.py                   55      0   100%
pcdsdevices/utils.py                       63     13    79%   12-14, 60, 128-137, 156
```

**Comment by ZLLentz** [comment]
Ok and codecov double confirms the diff coverage is 100%. I'm confident that this is OK.

A cool thing about pint is that we can register custom units. So that's kind of neat if we have that sort of need.

**Comment by hhslepicka** [comment]
Just beware that Pint has some issues with constants and wrong values. I did not experience this myself. This comes from feedback from a different project.

**Comment by ZLLentz** [comment]
Thanks for the disclaimer @hhslepicka. I hope we don't run into the same issue... I haven't dipped into the constants in `pint` yet. Right now we're just converting length and time quantities so hopefully we can coast along until things are updated/fixed upstream.

Shouldn't we use scipy constants for that anyway? I'm having trouble remembering how these packages are laid out.
At any rate, I'm sick of the various issues with using `cf-units` and will be welcoming of a new set of issues.

**Pull request merged**
