### PR TITLE
DOC: release note extender

### PR DESCRIPTION
**Pull request by ZLLentz**
An uncoordinated simultaneous effort with a similar goal as #583

### CODE REVIEW

**Comment by klauer** [comment]
Looks pretty clean to me. I like the goal of it being more of a real command-line tool instead of a helper script.

I have no issue whatsoever with closing my PR. Still it would be interesting to compare the output as a logic check for both of ours :+1:

**Comment by ZLLentz** [comment]
To compare with the other PR:
```
Writing out release notes file


v2.0.0 (2020-09-17)
===================

API Changes
-----------
- :class:`BaseInterface` no longer inherits from :class:`ophyd.OphydObject`.
- The order of multiple inheritance for many devices using the LCLS-enhanced
  :class:`BaseInterface`, :class:`MvInterface`, and :class:`FltMvInterface` has
  been changed.
- :class:`~pcdsdevices.interface.Presets` ``add_hutch`` (and all similar
  ``add_*``) methods no longer require a position.  When unspecified, the
  current position is used.

Features
--------
- Moves using mv and umv will log their moves at info level for interactive
  use to keep track of the sessions.
- Add ``user_offset`` to :class:`~pcdsdevices.signal.UnitConversionDerivedSignal`,
  allowing for an arbitrary user offset in user-facing units.
- Add ``user_offset`` signal to the :class:`pcdsdevices.lxe.LaserTiming`, by
  way of :class:`~pcdsdevices.signal.UnitConversionDerivedSignal`, offset
  support.
- Epics motors can now have local limits updated per-session, rather than
  only having the option of the EPICS limits. Setting limits attributes will
  update the python limits, putting to the limits PVs will update the limits
  PVs.
- Add PVPositionerDone, a setpoint-only PVPositioner class that is done moving
  immediately. This is not much more useful than just using a PV, but it is
  compatibile with pseudopositioners and has a built-in filter for ignoring
  small moves.

Device Updates
--------------
- CCM energy limited to the range of 4 to 25 keV
- CCM theta2fine done moving tolerance raised to 0.01
- Beam request default move start tolerance dropped to 5eV

Bugfixes
--------
- Fix bug on beam request where you could not override the tolerance
  via init kwarg, despite docstring's indication.
- Tab completion for many devices has been fixed. Regression tests have been
  added.
- Adds hints to the :class:`pcdsdevices.lxe.LaserTiming` class for
  ``LiveTable`` support.
- Fix issue where converting units could incur time penalties of up to
  7 seconds. This should take around 10ms now.
- Fix issue where putting to the limits property would update live PVs,
  contrary to the behavior of all other limits attributes in ophyd.
- Fix issue where doing a getattr on the limits properties would fetch
  live PVs, which can cause slowdowns and instabilities.
- Rework BeamEnergyPositioner to be setpoint-only to work properly
  with the behavior of the energy PVs.
- FltMvPositioner.wm will now return numeric values if the position
  value is a tuple. This value is the first element of the tuple, which
  for pseudo positioners is a value that can be passed into move and have
  it do the right thing. This resolves consistency issues and fixes bugs
  where mvr and umvr would fail.
- Tweak will feel less "janky" now and give useful feedback.
- Tweak now accepts + and - as valid inputs for changing the step size.
- Tweak properly clears lines between prints.
- umv will now properly display position and completion status after a move.
- Fix bug in PulsePickerInOut where it would grab only the first section of
  of the PV instead of the first two
- Fixed a race condition in the EventSequencer device's status objects. Waiting
  on these statuses will now be more reliable.

Maintenance
-----------
- Establish DOC conventions for accumulating release notes from every
  pull request.
- Use more of the built-in ophyd mechanisms for limits rather than
  relying on local overrides.
- Tweak refactored for maintainability.

Contributors
------------
- zrylettc
- zlentz
- klauer
- zllentz
- pennebak

```

**Comment by ZLLentz** [comment]
A quick scan suggests the following diffs:
- I added a header
- You sorted the contributors

**Comment by klauer** [comment]
Looks good! Let's go with it.

Randomly sorting contributors may be more fair than alphabetical order here for you guys with `z*` names...

**Comment by ZLLentz** [comment]
I'm not sure if it's random or first-come-first-serve...
I think we should sort to make it easier to pick out typos

**Pull request merged**
