### PR TITLE
ENH: add laser destination 1 (LD1)/diagnostics box to BTPS

### LINKED ISSUE #1113: Laser BTPS: Add diagnostics box to list of destinations (LD1)
## Current Behavior
* LD1 is not exposed in the current ophyd device `BtpsState`

## Expected Behavior
* LD1 should be exposed in the current ophyd device `BtpsState`
* Screens should be modified to add LD1 to the tab list
* Modifications to the BTMS GUI _may_ also be required

### PR DESCRIPTION
**Pull request by klauer**
## Description
- Added laser destination 1 (LD1), where a diagnostics box is installed, to  the Laser Beam Transport System (BTPS) state configuration.
- Updated ``BtpsState`` comments and logic to help guide future port additions.
- Updated BTPS screens for showing the new laser destination. BTMS UI changes not required so far.

TODO
- [x] Update BTPS screens to add new LD1/LSx combinations
- [ ] Check with Tyler about lack of PVs for LD1 valves (image)

## Motivation and Context
Closes #1113 

## How Has This Been Tested?
Interactively

## Where Has This Been Documented?
Issue and PR text.

To add a new laser destination to the BTPS, do the following:
1. Update `pcdsdevices.laser.btms_config`:
    - Add the `DestinationPosition.ldX` to `valid_destinations`
    - Add a description in the `DestinationPosition.description` dictionary
2. Update `pcdsdevices.laser.btps`
   -  Uncomment or add the `ldX` component in `BtpsState`
3. Update plc-las-bts
   - Follow https://github.com/pcdshub/lcls-plc-las-bts/issues/14 for the new destination
   - Rebuild and download the project into the PLC
4. Update the screens (see the screenshots below)
   - Add a new tab to `btps_config.ui`. Ensure `macros` property has the correct `DEST` (`LTLHN:LDx`)
   - Add a new column to `btps-overview.ui`. Hold control and drag each item to the last column. Undo and retry if designer makes a new row/column accidentally. Change the prefixes for each of the widgets to `LTLHN:LDx:...`
   - Add a new tab to `btps.ui` (right click, insert page after this page). Copy over the embedded display from another tab and right click to set the layout to make the widget take up the entire tab. Set the `DEST` macro in the embedded display to `LTLHN:LDx:`
5. Run `pydm pcdsdevices/ui/btps.ui` to verify that things render appropriately
    - If there's no title for the columnin the overview, double-check that the PLC project has been updated. It's important to keep the information there and not just in the screens.
<details>
<summary> ⬇️ ⬇️ ⬇️  Screenshots for .ui file updates ⬇️ ⬇️ ⬇️ </summary>
Tab in btps_config.ui

image

New column
image

New column change prefixes:
image

New tab
image

</details>

## Screenshots (if appropriate):

This PR as-is is enough to show LD1 in the BTMS:

image

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on GitHub Actions
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by slactjohnson** [comment]
Thanks Ken! I've added this information to our BTS documentation here: https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=376442025

I talked to the laser group and apparently there is no gate valve in front of the diagnostic box, just a viewport, which kind of makes sense but is annoying because the logic will be different for this particular output. 

We should discuss how best to deal with this.

**Comment by klauer** [comment]
We'll have to figure out how to hack it in at the PLC level - making an associated _imaginary_ gate valve always show a good/valid state. I think that'd be better than adjusting the protection logic to special-case LD1.

At the BTMS UI level it's not a big deal, we can choose another icon and disable all of the valve-related stuff.

**Comment by klauer** [comment]
Looks like we never merged this, @slactjohnson . I think there weren't any issues with this - please refresh my memory if that's not the case

**Review by slactjohnson — APPROVED** [review]
LGTM. Thanks Ken!

**Review by tangkong — APPROVED** [review]
The changes here look good to me, the path toward doing this again is clearer now too.  +1 for confluence docs.  I agree that we can loop back to this if anything needs changing, best to not let this get too stale

**Review by ZLLentz — APPROVED** [review]
Looks good + very detailed docs

**Pull request merged**
