### PR TITLE
ENH: PIM custom status

### LINKED ISSUE #674: Custom Status Print for PIM
## Expected Behavior
```
In[1]: yag2
Out[1]:
XPP SB3 PIM: OUT      
Y position: -50.00 [mm]
Navitar Zoom: 10.0 [%]   Focus: 0.02 [mm]
```

## Context

https://docs.google.com/document/d/1dmalnT4xLPWoJESsMHTxzIyzlGCBgTQjGNYwDhU-pzo/edit#heading=h.ylcn31lb55xr

### PR DESCRIPTION
**Pull request by cristinasewell**
Override the status info handler for pim.
 - [x] need to check about the focus...

## Motivation and Context

Trying to implement and close #674 

## How Has This Been Tested?

Not sure if I'm testing this correctly:
```
In [3]: pim_f = PIMWithFocus(prefix='CXI:DG1:PIM', name='yag')

In [4]: pim = PIM(prefix='CXI:DG1:PIM', name='yag')

In [5]: pim_f
Out[5]:
CXI DG1 PIM: OUT
Y Position: -51.9995 [mm]
Navitar Zoom: 0.6180 [%]  Focus: ERROR [None]

In [6]: pim
Out[6]:
CXI DG1 PIM: OUT
Y Position: -51.9995 [mm]
Navitar Zoom: 0.6180 [%]
```
## Where Has This Been Documented?

Docstring 

## Pre-merge checklist
- [ ] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [x] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by ZLLentz** [comment]
This looks reasonable to me. What's the sticking point about the focus?

**Comment by cristinasewell** [comment]
> This looks reasonable to me. What's the sticking point about the focus?

I assumed that we only get the focus and display it for the Pim with Focus - because the other ones did not have `focus` in their `status_info` so I though they don't have focus - but wanted to double check if that's the case, or if I should somehow get a `focus` from somewhere else.

**Comment by ZLLentz** [comment]
Yes, that is correct! Some of these do not have focus. We have an unfortunate situation where the LCLS-I PIMs have a wide variety of flavors (with or without zoom, with or without focus...), so we don't need to display at all for the features that do not exist.

**Comment by cristinasewell** [comment]
> Yes, that is correct! Some of these do not have focus. We have an unfortunate situation where the LCLS-I PIMs have a wide variety of flavors (with or without zoom, with or without focus...), so we don't need to display at all for the features that do not exist.

I should check if I have a `Zoom` then too, i'm currently assuming not checking that...

**Comment by ZLLentz** [comment]
I think this is just missing the pre-release docs before merging, it looks good to me

**Review by ZLLentz — APPROVED** [review]

**Pull request merged**
