### PR TITLE
ENH: BeckhoffSlits UI

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

- Make a typhos UI template for the BeckhoffSlits class using @ghalym 's pydm slit elements
- Make an example/guide as to how to make typhos templates
https://confluence.slac.stanford.edu/display/~zlentz/Converting+a+PyDM+UI+to+a+Typhos+Template%3A+Learning+by+Example
(I think some version of this will end up in the typhos docs and in the internal pcds docs)

Image:
image

## Motivation and Context

- Auto slits screen is kind of rough
- TMO wants the two screens to be the same
- I want the two screens to be the same
- Maggie already had some slit elements available from her previous screen work
- I wanted to make an example/tutorial for how to make typhos templates

## How Has This Been Tested?

Interactively

## Where Has This Been Documented?

Added pre-release notes
Recording the development process in my confluence page for use in docs later

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Review by ghalym — APPROVED** [review]
This is an Awesome screen! The one thing that is missing are the RTDs. They are only installed on the power slits: SL1K0, SL2K0 and SL1L0.
Thanks Zach.

**Review by klauer — APPROVED** [review]
Screens look really nice! Don't forget to do the pre-release notes. 

I'll take a look at the confluence docs separately (and maybe add some comments there if I see anything).

**Comment by ZLLentz** [comment]
> The one thing that is missing are the RTDs
Good catch, I'll go back for these
> Don't forget to do the pre-release notes
Oops

**Comment by ZLLentz** [comment]
Here's with the temperatures:

**Pull request merged**
