### PR TITLE
HXR Stubs

### PR DESCRIPTION
**Pull request by hhslepicka**
Some devices to spin the Home Screen. This was created to test the home screen...
Feel free to push to this branch as desired.

### CODE REVIEW

**Comment by ZLLentz** [comment]
I plan to use this as an example to set up the stubs for all the lcls 2 devices, have not decided if I'm pushing back to this one or making another pr

**Comment by ZLLentz** [comment]
I think we just need to settle the class names and populate the rest of the classes

**Comment by slacAWallace** [comment]
Talked with @ZLLentz about this a bit. I am going to organize things based around the functional component names from the LCLSII naming convention, and create classes for all the fungible names that we have for variants. I'll make this stuff with the devices from the [device lists](https://docs.google.com/spreadsheets/d/1SS4OfvrTY0TCQKjtgCm93OCnOSuVKPXwQWIKTwrGoh8/edit#gid=454186068) in mind so we can fill in happi asap.

**Comment by klauer** [comment]
Closing in favor of #377

**Pull request closed without merging**
