### PR TITLE
add PID kill at the end of CCM motion

### PR DESCRIPTION
**Pull request by vespos**
## Description
Kill CCM's PID loop at the end of a move command

## Motivation and Context
The PID loop keeps looking for the final position forever. The motor thus runs at too high duty cycles, heats up and causes vacuum spikes in the chamber. This has led to MPS trips. In addition, there is serious potential to fry the motor itself, as it is run too intensively.

## How Has This Been Tested?
Currently running at XPP for CCM experiments. Still waiting on confirmation that this all works fine before finalizing this pull request

## Where Has This Been Documented?
Docstring of the new move function.

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on travis
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Review by tangkong — COMMENTED** [review]
This looks good to me, and is verbatim what you had implemented / discussed with zach and I.  I assume this works locally, but want to verify that this is a fix that should be applied to all CCM's (which seem to be only `xpp_ccm` and `xcs_ccm`)

**Comment by tangkong** [comment]
Tests are complaining now that we're trying to actually interact with the fake pid in the test suite as well

**Comment by vespos** [comment]
@tangkong The past couple beamtimes did not have any further issues with the CCM. @tangkong  can you please review / approve this again?
I am adding the pre-release doc in an upcoming commit.

**Review by tangkong — APPROVED** [review]
Looks good to me, and if this works in production I don't have much to complain about.  We should be ok to merge after pre-release notes

**Pull request merged**
