### PR TITLE
MNT: Elliptec 'stop' signal conflict

### LINKED ISSUE #645: Elliptec 'stop' signal conflicts with BlueSky interface
## Expected Behavior
The elliptec class works perfectly. 

## Current Behavior
A signal on the elliptec currently interferes with the BlueSky interface. 

## Possible Solution
Rename the signal. 

## Steps to Reproduce (for bugs)
Instantiate an elliptec motor. 

## Context
This prevents instantiation of a elliptec device, which are used throughout the laser system. 

## Your Environment
pcds-3.4.0

### PR DESCRIPTION
**Pull request by slactjohnson**
## Description
Changed the 'stop' signal to 'stop_optimize' in the elliptec module.

## Motivation and Context
This resolves a conflict with the BlueSky interface. 

Closes #645 

## How Has This Been Tested?
Tested interactively using a stage in the Heinz lab. 

## Where Has This Been Documented?
The code. 

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]
LGTM! Sorry for not catching on first review.

**Comment by slactjohnson** [comment]
@ZLLentz Thanks. I don't know how I missed this during testing.

**Comment by ZLLentz** [comment]
I'm wondering if we can do some generic checks on if our signals are overwriting parent class methods, since that kind of conflict is probably always an error.

**Comment by klauer** [comment]
This should have raised `TypeError`, shouldn't it have?

https://github.com/bluesky/ophyd/blob/33bfc595ac2862aede96f023296f564832144551/ophyd/device.py#L33-L41


```
TypeError: The attribute name(s) {'stop'} are part of the bluesky interface and cannot be used as component names. Choose a different name.
```

**Comment by slactjohnson** [comment]
@klauer Yeah, it did when I tried to instantiate it as part of a TuttiFrutti. Somehow I didn't see this when I was testing; maybe I had a different name for the signal initially and changed my mind and just committed? I just can't remember. I was seriously irritated on Friday when I discovered this since this should not happen. I guess the real answer is that I need to take a bit of time to do things right and add test suites for all these new laser devices. I will do better.

**Comment by ZLLentz** [comment]
I created a new issue for making sure we import/instantiate all of our classes in the test suite.

**Comment by klauer** [comment]
@slactjohnson I think it's not really such a big deal, but I for sure understand your frustration. 

As regular pcdsdevices maintainers, I think we can do better here too by automatically importing all modules in the pcdsdevices tree as Zach indicated in #647. We might also start paying more attention to coverage at some point.

**Pull request merged**
