### PR TITLE
MNT: Clean up ad detector classes

### PR DESCRIPTION
**Pull request by ZLLentz**
WIP: See #220

### CODE REVIEW

**Comment by teddyrendahl** [comment]
Also addresses #120

**Comment by teddyrendahl** [comment]
Few comments:

1) I don't think `Stats` should be enabled by default. I see the benefit of having it declared as a `Component` but most AreaDetector set ups won't want this enabled. 
2) Don't we want `Image1` and `Image2`? Shouldn't we be setting at least one of these to a specific rate for the viewer?
3) I'm not sure I like the name `DefaultAreaDetector` I think I would prefer `PCDSAreaDetector` but can't justify this with any logic.

**Comment by ZLLentz** [comment]
1. Agree on not enabling `Stats` by default. I started from a long list of stage sigs and wasn't sure how far to cut it down.
2. Assumed we only care about the low-rate or ROI image in Python 99% of the time
3. No preference on the name, happy to change it

**Comment by ZLLentz** [comment]
Actually I'm backtracking on point 1 a bit. When do we stage an areadetector but not want the stats?

**Comment by teddyrendahl** [comment]
I think we might not be imagining the same endpoint for this device.

**Comment by ZLLentz** [comment]
@teddyrendahl I'd at least like to finalize class names here so I can work on other issues that need a detector subclass.

**Comment by ZLLentz** [comment]
I will change the names and merge the PR, then we need to have a larger discussion about cleaning up this file and the other two in our areadetector dir

**Pull request merged**
