### PR TITLE
CI: unpin numpy in CI

### PR DESCRIPTION
**Pull request by tangkong**
## Description
- Unpins numpy in CI

## Motivation and Context
Numpy was previously pinned due to a numba build not yet existing.  This was pinned in https://github.com/pcdshub/pcdsdevices/pull/1100

## How Has This Been Tested?
through CI in theory

## Where Has This Been Documented?
This PR

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on GitHub Actions
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by tangkong** [comment]
pip 3.12 build fails due to slaclab/timechart using deprecated versioneer framework.

**Comment by ZLLentz** [comment]
This is still correct despite the ci failing at a later step

**Comment by ZLLentz** [comment]
Maybe we should merge this anyway (with pre-release notes) and handle the rest separately? Or do you want to push through timechart first?

**Comment by tangkong** [comment]
Oh I can finish this up.  Timechart will come later

**Review by ZLLentz — APPROVED** [review]

**Pull request merged**
