### PR TITLE
ENH: Gon custom status

### PR DESCRIPTION
**Pull request by cristinasewell**
This PR might need some more attention, because as of now I have added a custom status for two different classes: `BaseGon`, and `XYZStage` class. 

## Motivation and Context

Trying to tackle and close https://github.com/pcdshub/pcdsdevices/issues/682#issuecomment-733998450

## How Has This Been Tested?

```
In [1]: xpp_gon
Out[1]:
XPP Goniometer
H, V: 588.6461, 50.4013 [mm]
Theta, Pitch, Roll: -0.0468, 0.0400, 0.0282 [deg]
```
XYZStage:
```
In [5]: s
Out[5]:
XYZStage
X, Y, Z: 8.6988, -12.7856, 0.4693 [mm]
```
## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on travis
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by cristinasewell** [comment]
we can probably wait for this https://github.com/pcdshub/pcdsdevices/pull/711 guy to be merged and then I can also add some info in the status print for `Kappa` about the pseudo motors? I am not sure if we even want that?

**Comment by klauer** [comment]
I'd bet they'll want some info about Kappa, formatted similarly. I think it's just fine to add that format change to #711.

**Comment by cristinasewell** [comment]
> I'd bet they'll want some info about Kappa, formatted similarly. I think it's just fine to add that format change to #711.

Sounds good, I can add the format status to the Kappa class in #711 and then remove it from here.

**Review by ZLLentz — APPROVED** [review]
Not much to say here, looks clean

**Pull request merged**
