### PR TITLE
MAINT: pre-commit autoupdate

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

I ran `pre-commit autoupdate`

## Motivation and Context

Something in pre-commit is broken on the other pull requests

## How Has This Been Tested?

n/a

## Where Has This Been Documented?

pre-release notes

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [ ] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Review by tangkong — APPROVED** [review]
Provided tests pass

**Comment by ZLLentz** [comment]
Well, the pre-commit runs now but seems to have forgotten the line length settings

**Comment by ZLLentz** [comment]
The testing failure is unrelated

**Comment by ZLLentz** [comment]
This passes now, but we may opt to close in favor of just merging #1102

**Comment by klauer** [comment]
Closed in favor of #1102 which has other large changes, including `pre-commit autoupdate` and flake8 fixes that were required once our config was properly being used

**Pull request closed without merging**
