### PR TITLE
 TMO GMD device classes

### PR DESCRIPTION
**Pull request by KaushikMalapati**
## Description

Adding devices from /cds/group/pcds/pyps/apps/hutch-python/tmo/tmo/tmo_beamline_control.py

## Motivation and Context

https://jira.slac.stanford.edu/browse/ECS-4058

## How Has This Been Tested?

Has not been tested, but will do so programmatically

## Where Has This Been Documented?

Pre-release notes

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on GitHub Actions
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by KaushikMalapati** [comment]
I haven't added the undulator devices or beamline devices since they seem fairly tmo specific. Does it make sense to add them to pcdsdevices?

**Comment by ZLLentz** [comment]
Sorry for the delay on reviews here, I'll be going through my github backlog today, starting with this PR.

**Comment by ZLLentz** [comment]
> I haven't added the undulator devices or beamline devices since they seem fairly tmo specific.

I think the TMO devices are definitely best-off left in TMO (there's a lot of them here)
We might want to bring in the undulator devices since they are shared, but maybe not in the same PR. There's some weird code in there that we should evaluate first.

For this PR, everything looks normal and good- a solid, faithful port. I'm going to go through it by hand and check if there's anything James put in there that I think is slightly off, such as the kinds and the docs

**Comment by ZLLentz** [comment]
Actually, thinking about it more lucidly- maybe it's more productive to merge this as-is, and then do a follow-up myself with a bunch of banal changes? It seems silly to ask you to change minor things when the original device source isn't you, and the decisions involved probably need more than just me to figure out anyway. The port is clean.

**Comment by KaushikMalapati** [comment]
I added many of the docs and changed some of the kinds (most were originally hinted). Should I change back the kinds to what James had and then merge? I was thinking that having most kinds as hinted would have too much information on the device screen but that might not have been a good idea.

**Comment by ZLLentz** [comment]
I think if you have/had specific ideas about kinds/docs it's good to include the changes- I had the same opinion as you re: too many hinted, etc.
I suspect that if I brought this list of docs/kinds in front of a few other engineers we'd be able to accumulate some additional ideas for some of the empty docs and help us identify read-only variables and figure out which things should be kind=config

**Comment by KaushikMalapati** [comment]
In that case, feel free to merge. I will watch out for another pr related to this to see what sort of changes are made.

**Review by ZLLentz — APPROVED** [review]

**Pull request merged**
