### PR TITLE
Added HV_DI PV into PIPPLC class 

### PR DESCRIPTION
**Pull request by jozamudi**
## Description

Added HI_DI PV to PIPPLC class to show high voltage input for diagnostics. Also removed qpc_name as PV seems to no longer exist.

## Where Has This Been Documented?

Screenshot_20240827_115011

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on GitHub Actions
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Review by tongju12 — APPROVED** [review]
lgtm. Thanks.

**Comment by ghalym** [comment]
@jozamudi the qpc_name is a working pv. It might not have worked in this specific case, but it works for all other pumps. Please make a new PR to return this pv where it originally was. 
Thank you.

**Comment by ZLLentz** [comment]
I'm going to make a PR that fixes the release notes for v8.6.0 to add the missing note about the removal of `qpc_name` (it isn't present in the pre-release notes here, so it was missed). Since I'll already be here making repo changes, I'm going to add `qpc_name` back in.

We should be careful to loop vacuum SMEs in to changes to shared vacuum components in the future. At some point this will be enforced/automated with code owners and we won't have to think so much about who should be reviewing what.

**Comment by ZLLentz** [comment]
Follow-up PR is #1288

**Comment by jozamudi** [comment]
Hi all, sorry ive missed this. Thanks Zach for following up and creating the PR. Thanks Maggie for calling this out. Ill make sure to loop in vacuum SMEs next time I make changes to shared vacuum components.

**Pull request merged**
