### PR TITLE
MNT: moved PTMPLC's entries from omitted to normal so it can be used …

### PR DESCRIPTION
**Pull request by slacAdpai**
…immediately after opening expert screens.

## Description
moved PTMPLC's entries from omitted to normal so it can be used immediately after opening expert screens.

## Motivation and Context
The user and I were getting tired of going into omitted to change the backing pressure setpoint and the inlet pressure setpoint. Having it in normal is already good enough.

## How Has This Been Tested?
No test is required.

## Pre-merge checklist
- [x] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on travis
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by ZLLentz** [comment]
Are these setpoints expected to be changed often and to be one of the first things you look at when inspecting the device? It seems super sketchy to me to change your mind entirely and go from "don't look at me" to "please look at me first." If they need to be changed often, then surely this is a `config` parameter, rather than a `normal` parameter, right?

**Comment by ZLLentz** [comment]
Also, "no test required" is 100% False, you need to at least run the code locally before we merge it into master

**Comment by slacAdpai** [comment]
> Also, "no test is required" is 100% False, you need to at least run the code locally before we merge it into master

How do I test the code locally?

**Comment by ZLLentz** [comment]
Activate a python environment with your code loaded and make sure it behaves how you like (e.g. open the screen). You may find that after switching to normal you may want to do other small tweaks that you didn't realize.

You can add your code to any python env by adding your `pcdsdevices` checkout to your `PYTHONPATH` variable

**Comment by ZLLentz** [comment]
e.g. `source pcds_conda`, `export PYTHONPATH=/path/to/my/pcdsdevices`

**Comment by slacAdpai** [comment]
@ghalym , @slacAWallace , @silkenelson  I have been hearing conflicting opinions on whether or not the turbo pump expert screens should hide the backing pressure setpoints and inlet setpoints or keep them in the config filter. What should be done?

**Review by ZryletTC — CHANGES_REQUESTED** [review]
Changes look good now, I assume you're still waiting to hear back on how hidden the setpoints should be. Just marking this to ensure it gets tested before merge.

**Comment by ZLLentz** [comment]
Any thoughts on what should be done here? A bunch of people were tagged for opinions and this pull request is sitting in review purgatory.

**Comment by ghalym** [comment]
> Any thoughts on what should be done here? A bunch of people were tagged for opinions and this pull request is sitting in review purgatory.

@slacAdpai Do we still need this? I think this was done because of the autosave issues and making it easier to get to them and re set them from the screen. 
Now these values are saved as persistent variables, so unless you 'reset cold' the PLC you won't lose these values.

**Comment by slacAdpai** [comment]
Yes, these changes are still needed. During operations, when changes are needed for all turbo pumps on a beamline. Opening up the omitted screen reduces the efficiency of making changes. The beamline scientist usually do not change setpoints but call on the controls engineer anyway. Creating this one extra hoop in theory is great but in practice is just a larger roadblock for the controls engineer.

**Comment by ghalym** [comment]
> Yes, these changes are still needed. During operations, when changes are needed for all turbo pumps on a beamline. Opening up the omitted screen reduces the efficiency of making changes. The beamline scientist usually do not change setpoints but call on the controls engineer anyway. Creating this one extra hoop in theory is great but in practice is just a larger roadblock for the controls engineer.

Which values do they often change? I thought these are safety setpoint that are set once and done.

**Comment by slacAdpai** [comment]
The tmo roughing valve has to change its setpoint during the pump down procedure. The safety setpoints are not always set in stone and can change depending what the scientist or vacuum experts assert. When this happens, the process takes longer than needed and is frustrating for the controls engineer. This entire pull request is feedback from the operations side. If it is not welcome, then so be it. I just wanted to log my request and be done with this.

**Comment by ghalym** [comment]
> The tmo roughing valve has to change its setpoint during the pump down procedure. The safety setpoints are not always set in stone and can change depending what the scientist or vacuum experts assert. When this happens, the process takes longer than needed and is frustrating for the controls engineer. This entire pull request is feedback from the operations side. If it is not welcome, then so be it. I just wanted to log my request and be done with this.

I'm sorry Allen, I didn't mean to say its unwelcome. I was just trying to understand the requirements behind this, maybe there is room for improvement in the library (like the persistent variables) or maybe elsewhere.
I have no objection to this pull request. If we can attach information to this setpoint letting the operator understand the consequences for changing this value. The vacuum protection interlocks are only as good as these setpoint.

**Comment by ZLLentz** [comment]
Ok, so in summary:
- omitted bad
- normal best (current PR)
- config not quite correct (my suggestion, denied/ignored)

Can someone confirm?

**Comment by ZLLentz** [comment]
Ok, I will finish this PR myself for the purposes of doing the tag

**Review by ZLLentz — APPROVED** [review]

**Pull request merged**
