### PR TITLE
WIP/ENH: proposal for alternative states customization + mr1l0_homs fix

### PR DESCRIPTION
**Pull request by klauer**
## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on travis
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by klauer** [comment]
@ZLLentz an idea here - not sure if better or worse than the status quo, but the excessive explicit subclassing was getting to me.

**Comment by ZLLentz** [comment]
This is a really interesting framing- the pattern (classmethod to create a subclass, pass into a component) might be useful beyond the scope here. Explicit and compact, I like it.

**Comment by klauer** [comment]
This could potentially be a generic pattern applied to the base interface; `.customized(component_name=dict(**update_args))`

I'm trying to imagine how it could be abused. Perhaps the lack of a subclass existing for inheritance purposes means that it "dies" at a single level of ugliness and can't be abused further. Not sure.

**Comment by klauer** [comment]
I think this could have potential, but we already have a solution for now. Can revisit later; closing

**Pull request closed without merging**
