### PR TITLE
535 lxt ttc alt

### PR DESCRIPTION
**Pull request by klauer**
Alternate to #551, for your consideration.

Limit handling is probably wrong here.

### CODE REVIEW

**Comment by ZLLentz** [comment]
This one forgoes the combined device and does the synchronous move in a separate function call?

**Comment by klauer** [comment]
Yes, at the end of `pcdsdevices/lxe.py` (`lxt_ttc`).

**Comment by ZLLentz** [comment]
I think both formulations are good. It's hard for me to approve either of them when the other exists though, since I don't understand the beamline case for doing it one way vs the other.

**Comment by klauer** [comment]
I readily admit I do not understand the requirements - so this is a something along the lines of: try multiple options, throw them at (over?) the wall and see what sticks.

**Comment by klauer** [comment]
Seems like #551 will stick

**Pull request closed without merging**
