### PR TITLE
Added LAMPFlowCell class to lamp_motion.py for the x454 configuration

### PR DESCRIPTION
**Pull request by Mbosum**
## Description

Added LAMPFlowCell class at the end of lamp_motion.py to connect to motor PVs associated with the x454 configuration of LAMP motion components of the LAMP IP1 endstation. 

## Motivation and Context

The dVMI will be taken off of LAMP for x454 in exchange for a 4 axis flow cell manipulator. These axes need to be reflected in the motion control GUI.

## How Has This Been Tested?

I tested the module with flake8 it came back clean.

(pcds-4.2.0) pslogin02:pcdsdevices bosum123$ flake8 ./lamp_motion.py
(pcds-4.2.0) pslogin02:pcdsdevices bosum123$

I also tested whether I can make a device with it to verify the PV and component names:

image

## Where Has This Been Documented?

There is a docstring for the class. 

Confluence documentation is found here: 
https://confluence.slac.stanford.edu/display/L2SI/LAMP+Motion+System#LAMPMotionSystem-MechatronicParameters 

## Pre-merge checklist
- [ ] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [ ] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by ZLLentz** [comment]
Do you expect all the PVs to show disconnected as in your test above?

The code looks good, the disconnected PVs are concerning

**Comment by Mbosum** [comment]
Hi Zach, every time I have run for the wait_for_connection() test it has shown the PVs to be disconnected. Not sure of the significance either

**Comment by ZLLentz** [comment]
The point of that test is to not see an error. So whenever I see it erroring out, my conclusion is that either the code or the IOC is broken. The error message isn't a confirmation that the PVs are correct, it's a confirmation that "the following PVs are wrong".

**Comment by Mbosum** [comment]
it would make sense that the IOC would not work since I have not finished updating the LAMP motion twincat project with the new axes, rebuilt ioc etc.

**Review by ZLLentz — APPROVED** [review]
OK if you're sure this is on the IOC side then I'm happy to merge. This is all a procedure to save you from having to come back here a second time. And a third time. And a fourth time (for the same device)

**Pull request merged**
