### PR TITLE
ENH: try AT2L0 error summary/clearing with MultiDerivedSignal

### PR DESCRIPTION
**Pull request by klauer**
## Description
AT2L0 error summary and clearing utility using the new MultiDerivedSignal of #970 

## Motivation and Context
* cc @mkestra - this could be a good basis for a new implementation, or at least a sample of how to use it.
* AT2L0 has a lot of blades and a lot of error signals which are hard to find on screens

## How Has This Been Tested?
* Only tested the readback behavior
* Tried a `put` but just to see that the code executed as I did not have write access on psbuild

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on travis
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by mkestra** [comment]
much appreciated, this should be a great example for what I need to do and working with signals in general.

**Comment by mkestra** [comment]
some docs would be much appreciated, but in the mean time, I'll take it as an opportunity to review the documentation and toy with your example to get a better feel for how it works.

**Comment by klauer** [comment]
In typhos, these signals are available through the normal hutch-python-style dotted attribute access, as in:
`sig://at2l0.error_summary`
which looks like this in typhos when used in a `PyDMLabel`:
Screen Shot 2022-04-04 at 9 50 13 AM

Or alternatively - this is *not* recommended  in general - with the underscored name, as reported during data collection:
Screen Shot 2022-04-04 at 9 50 16 AM

**Comment by klauer** [comment]
Superseded by #996

**Pull request closed without merging**
