### PR TITLE
Qmini v2

### LINKED ISSUE #1120: Qmini updates
## Current Behavior
The qmini IOC has had some work done, and now it wants to strut its stuff. The Qmini needs a few PVs changed to support the recent changes to the IOC. 

Additionally, EVR and TPR support was added, meaning this may depend somewhat on #1118 and #1119. Support for soft-triggering (which is what is needed for dispersion scanning) could be done without the EVR/TPR support. 

## Context / environment
The Qmini is used throughout the MODS system and, more pressing than that, we'd like to use the updated Qmini in the las-dispersion-scan application. 

## Suggested Solution
The most expedient solution for dispersion scanning is to update the soft-trigger PVs and leave the EVR/TPR updates for later.

### PR DESCRIPTION
**Pull request by slactjohnson**
## Description
I updated some PVs in the QminiSpectrometer device. I updated the QminiSpectrometer.embedded.ui screen to reflect this as well. 

## Motivation and Context
Closes #1120 

## How Has This Been Tested?
Tested on a qmini in the laser lab. 

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on GitHub Actions
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by slactjohnson** [comment]
Failed check seems unrelated to this PR. It fails on lightpath?

**Comment by klauer** [comment]
Note that the Python 3.11 test is not required to pass:
image

The required tests are passing without issue.

**Comment by slactjohnson** [comment]
@christina-pino Can you give a quick review when you get a chance?

**Review by christina-pino — CHANGES_REQUESTED** [review]
The PVs added look good to me. However, the "scan_rate" was used by the qmini embedded screen. So now it is "blank". 
Screen Shot 2023-05-09 at 5 37 44 PM
I also verified all of the PVs pass through okay, which they do. 
Screen Shot 2023-05-09 at 5 39 19 PM

**Comment by slactjohnson** [comment]
This is strange, because I set this in the embedded file. If I call 
`pydm -m "prefix = LAS:LLN:QMINI:02" pcdsdevices/ui/QminiSpectrometer.embedded.ui`
from the top level of pcdsdevices the screen appears fine. 
I'm not sure why this would be. 
image
image

**Comment by slactjohnson** [comment]
Thanks, @christina-pino. If there's nothing else you want me to chance, can you approve the PR when you get a chance?

**Review by christina-pino — APPROVED** [review]

**Pull request merged**
