### PR TITLE
CLN: remove remaining pre-release notes

### PR DESCRIPTION
**Pull request by klauer**
## Description
The target for #1024 moved a few times and I neglected to delete the pre-release notes files for v6.2.0.

### Why not push to master and avoid judgment?

Instead of pushing to master to quietly correct my mistake, I'll accept the public shaming that comes along with this one.
However, I will not make release notes for this nor check the boxes.

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]

**Review by tangkong — APPROVED** [review]
Would the direct-push-to-master not get caught and reported by the slack bot? I didn't think there was a sneaky way to do this

**Comment by ZLLentz** [comment]
pushing to master would require some settings edit tomfoolery as well

**Comment by klauer** [comment]
'Twas but a joke, lads.

Travis has yet to see this PR. I don't see a point in cycling it for superfluous testing, and would request that we merge without CI here if you agree.

**Comment by ZLLentz** [comment]
I'm ok with merging this without Travis if Travis has disappointed us today

**Pull request merged**
