### PR TITLE
HACK: include janky LaserTiming fix from xpp/xcs live deployment

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Sleep a second whenever we move LaserTiming

## Motivation and Context

Things are bad, this works in prod, I have heard no complaints, and I have other things I'd prefer to work on.

### CODE REVIEW

**Comment by ZLLentz** [comment]
See #752 for a previous cleaner but very failed attempt

**Review by klauer — APPROVED** [review]
Works in prod ▶️ approve 👍

**Comment by klauer** [comment]
Oh, wait - `tests/test_lxe.py::test_lasertiming_dmov_pass FAILED                     [ 77%]` - test failure wasn't random, it appears.

**Comment by ZLLentz** [comment]
It's not so surprising that a test about dmov fails when we intentionally break dmov. I'll put a little bit of time into that.

**Review by ZryletTC — APPROVED** [review]
I don't like janky hack but better to merge than leave it in dev checkouts so 👍

**Pull request merged**
