### PR TITLE
DOC/REL: v8.4.0

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Release notes for the next tag, created via combining everyone's release notes together and proofreading a bit more closely than during PR review.

I'm asking for an optional review for everyone who contributed to this tag, to revise if I've misrepresented your contribution. You are not obligated to review now and we can edit the notes later if needed.

## Motivation and Context

It's long overdue for a tag.

## How Has This Been Tested?

I looked really closely at the docs build and checked for broken links and bad formatting. Seems OK.

## Where Has This Been Documented?

Only here

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on GitHub Actions
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Review by tangkong — DISMISSED** [review]
renders nicely for me 👍

**Review by aberges-SLAC — APPROVED** [review]
Looks good on my end! I have no complaints.

**Review by tangkong — APPROVED** [review]
I'm honestly never sure how much we should try to do the fancy sphinx hyperlinking.  But I'm happy you took the time to.

**Comment by baljamal** [comment]
`pcdsdevices.device.GroupDevice.needs_parent`  docs looks strange

**Comment by ZLLentz** [comment]
> `pcdsdevices.device.GroupDevice.needs_parent` docs looks strange

Thank you for pointing this out, it seems like this problem existed even prior to this PR but it should be fixed. I'll make a github issue for it.

**Comment by ZLLentz** [comment]
Here goes the EOD tag. Thanks everyone for the contributions! A bit 10-contributer tag coming right up!

**Pull request merged**
