### PR TITLE
PLC ophyd devices

### PR DESCRIPTION
**Pull request by jsheppard95**
Adding PLC devices to pcdsdevices. So far I have just added classes with the listed components found in the "PLC PV Names" spreadsheet, but this would be a good place to discuss more efficient inheritance from other pcds device classes as well as the desired functionality of each addition.

### CODE REVIEW

**Comment by ZLLentz** [comment]
These really really need to have class docstrings or maybe even more verbose class names, e.g. at the very minimum stuff like:
```
class GCC:
    """
    Cold Cathode Gauge

    Class to facilitate cold cathode gauge controls and readback on our
    Beckhoff PLCs. Controlled using the ADS driver using records from
    pytmc.
    """
    <code>
```

**Comment by ZLLentz** [comment]
Also, the submodule name `valve` has outlived it's useful life. It now contains stoppers, valves, gauges... I think some reorganization might be appropriate. We also need to think about if we want to add these new devices to the `device_types` submodule (and in the corresponding docs page)

**Comment by ZLLentz** [comment]
Last comment for now: I have no idea why that random lodcm unit test started failing...

**Comment by klauer** [comment]
Didn't some of these PVs change after February?

**Comment by ZLLentz** [comment]
Is this PR still relevant? E.g. should it be finished and merged at some future date or should it be dropped?

**Comment by jsheppard95** [comment]
> Is this PR still relevant? E.g. should it be finished and merged at some future date or should it be dropped?

I think it should just be dropped. These PVs are likely out of date and last I checked Tyler was working on this with Maggy. @ZryletTC Do you have a different PR for this?

**Comment by ZLLentz** [comment]
Is it #345?

**Comment by ZryletTC** [comment]
Yeah #345 replaces this one.

**Comment by ZLLentz** [comment]
No rush, just trying to clean up the PR queue

**Pull request closed without merging**
