### PR TITLE
ENH: laser btps devices + screens

### PR DESCRIPTION
**Pull request by klauer**
## Description
* Adds the laser system beam transport protection system (BTPS) devices.
* Adds custom PyDM screens for the BTPS.

## Motivation and Context
* Prototype PLC code is here: https://github.com/klauer/btps-prototype
    * This is now merged into the vacuum PLC: https://github.com/pcdshub/lcls-plc-las-bts
* Source PV simulator code is here: https://github.com/pcdshub/sim-ioc/pull/10

## How Has This Been Tested?
This succeeds:
```python
btps.wait_for_connection()
```

And the screens look OK, if complicated. An upstream PyDM change may be necessary to get appropriate spacing, but they work otherwise for now.

## Where Has This Been Documented?
There will be documentation on the implementation soon.

## Screenshots (if appropriate):

<details>
<summary>Screen</summary>
image
</details>

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by klauer** [comment]
Feedback from meeting with laser team:

* Expert screen launching - launch camera/stage screens when clicking range indicator descriptions (e.g., "NF Center X"). Or perhaps elsewhere?
* Move to specific configuration by user request
* Add "nominal" values for each stage
   - Add PVs to PLC
   - Seems like there's a desire for there to be a database (centralized store) for this, but out of the scope of this project
* Consider that watching the array counter for the centroid/stats plugin in areaDetector may be insufficient
   - What would be sufficient to allay any fears?
* Password protection decisions need to be made
 
@slactjohnson:
- Do you know the appropriate screens for the motors/area detectors?
- Any thoughts on what should be the minimum checks for area detector image updating? (Eric's suggestions)
- Am I forgetting anything in the above?

**Comment by klauer** [comment]
Got it - thanks!

As to "move to configuration X" - I made a note for it because they want the functionality, but should have marked it as "out of scope". The only thing in-scope here is adding the nominal value for each `RangeComparison` (motors + centroids)

**Comment by klauer** [comment]
Force-pushed to fix the proper PV prefix in a single commit (not `LAS:BTPS` but `LTLHN:BTPS`)

**Review by slactjohnson — APPROVED** [review]
LGTM! 👍

**Pull request merged**
