### PR TITLE
MNT: updated valve.py/classVFS/gfs_name with string=True

### PR DESCRIPTION
**Pull request by slacAdpai**
## Description
Fixed string=True kwarg described in conversation of #465

### CODE REVIEW

**Comment by hhslepicka** [comment]
Looks right! Did you test it?

**Comment by slacAdpai** [comment]
> Looks right! Did you test it?

I tested in ipython and got this. I don't think it passed... 
`pcds-3.3.0) [adpai@psbuild-rhel7-01 pcdsdevices]$ source dev_conda
(dev) [adpai@psbuild-rhel7-01 pcdsdevices]$ ipython
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pcdsdevices.valve import VFS                                                         

In [2]: vfs = VFS('TV3L0:VFS:01', name='vfs')                                                     

In [3]: vfs.get()                                                                                 
Out[3]: 
VFSTuple(valve_position=0, vfs_state=5, request_close=0, request_open=0, reset_vacuum_fault=1, override_mode=0, override_force_open=0, gfs_name=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8), gfs_trigger=0, position_close=0, position_open=1, vac_fault_ok=1, mps_ok=1)
`

**Comment by ZLLentz** [comment]
`dev_conda` might be doing some shenanigans that override your personal dev. You can check via:
```
import pcdsdevices
pcdsdevices.__file__
```

**Comment by slacAdpai** [comment]
> pcdsdevices.__file__

Yes, it is going to the main repository. I tried using pcds_conda but it is broken because schema is not currently loaded on there.
`In [4]: pcdsdevices.__file__                                                                      
Out[4]: '/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/__init__.py'
`

**Comment by slacAdpai** [comment]
Awesome! It works!

**Pull request merged**
