### PR TITLE
MNT: Enum is not a valid read type, IntEnum is

### LINKED ISSUE #757: Error Scanning XCS Attenuator
## Expected Behavior

Should be able to scan

## Current Behavior

Error on read:
Cannot determine appropriate bluesky data type for enum BladeStateEnum
https://pswww.slac.stanford.edu/lgbk/lgbk/XCS_Instrument/ws/attachment?entry_id=6029912894ef926a1d839cd4&attachment_id=6029912794ef926a1d839cd1&prefer_preview=False

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

bluesky expects all items to be clearly typed, this makes this item clearly typed.

## Motivation and Context

closes #757

## How Has This Been Tested?

see #757 

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Test suite passes locally
- [x] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by ZLLentz** [comment]
Should consider if this warrants follow-ups for expanded unit tests

**Review by klauer — APPROVED** [review]
Looks good to me, glad it worked. (:+1: for doing the actual work 😁 )

As for unit tests, could we have caught this with the sim object?
Also, is this our only `enum.Enum` in pcdsdevices?

**Comment by ZLLentz** [comment]
I see an `enum.Enum` in `state.py` that keeps track of the state positioner magic and a "Commands" `Enum` in `valve.py`
Might as well change them both, right?

**Comment by ZLLentz** [comment]
After some thinking, the REAL shortest way to see the issue is:
```
In [1]: xcs_attenuator.describe()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-2f71a44381d3> in <module>
----> 1 xcs_attenuator.describe()

/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/ophyd/device.py in describe(self)
   1254         res = super().describe()
   1255         for _, component in self._get_components_of_kind(Kind.normal):
-> 1256             res.update(component.describe())
   1257         return res
   1258

/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/ophyd/device.py in describe(self)
   1254         res = super().describe()
   1255         for _, component in self._get_components_of_kind(Kind.normal):
-> 1256             res.update(component.describe())
   1257         return res
   1258

/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/ophyd/signal.py in describe(self)
    410             val = self._readback
    411         return {self.name: {'source': 'SIM:{}'.format(self.name),
--> 412                             'dtype': data_type(val),
    413                             'shape': data_shape(val)}}
    414

/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/ophyd/utils/epics_pvs.py in data_type(val)
    320             return json_type
    321
--> 322     raise ValueError(
    323         f'Cannot determine the appropriate bluesky-friendly data type for '
    324         f'value {val} of Python type {type(val)}. '

ValueError: Cannot determine the appropriate bluesky-friendly data type for value BladeStateEnum.OUT of Python type <enum 'BladeStateEnum'>. Supported types include: int, float, str, and iterables such as list, tuple, np.ndarray, and so on.
```
This implies we should be calling the bluesky api (read, describe) on every device. I'll double-check this on a sim device too.

**Comment by klauer** [comment]
> I see an enum.Enum in state.py that keeps track of the state positioner magic and a "Commands" Enum in valve.py
Might as well change them both, right?

If they're exposed by ophyd components, then definitely. Otherwise, meh?

**Comment by ZLLentz** [comment]
Fair enough. They are definitely not exposed by ophyd components, so I will leave them for now.

A simple `.describe()` test of the fake device definitely exposes this bug. I will include the test I wrote in this PR for completeness, and make an issue for some sort of "collect all the fake devices and call read, describe" issue.

**Comment by klauer** [comment]
Sounds good. Since we have the test suite device aggregation functions already, I think it will help jump-start #760. 👍

**Pull request merged**
