### PR TITLE
Mpod channels

### PR DESCRIPTION
**Pull request by cristinasewell**
Added a MPODChannel object. 

## Motivation and Context

Trying to implement and close https://github.com/pcdshub/Bug-Reports-and-Requests/issues/50
## How Has This Been Tested?

Locally only.

## Where Has This Been Documented?

Doctring.

## Pre-merge checklist
- [ ] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [x] Test suite passes on travis
- [x] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by ZLLentz** [comment]
I did a bit of snooping on the XPP screens as a first-pass check. Here is what their control screen looks like on my screen:
image

The top is a low voltage module, the bottom is a high voltage module. Each has 8 channel objects associated with it. The following sample PVs are common between the two:
```
XPP:R39:MPD:CH:0:GetVoltage.DESC
XPP:R39:MPD:CH:0:SetSwitch Off
XPP:R39:MPD:CH:0:SetSwitch On
XPP:R39:MPD:CH:0:SetSwitch Emer
XPP:R39:MPD:CH:0:SetSwitch Reset
XPP:R39:MPD:CH:0:SetSwitch Clr
XPP:R39:MPD:CH:0:GetSwitch
XPP:R39:MPD:CH:0:SetVoltage
XPP:R39:MPD:CH:0:GetVoltageMeasurement
XPP:R39:MPD:CH:0:GetTerminalVoltageMeasurement
XPP:R39:MPD:CH:0:SetCurrent
XPP:R39:MPD:CH:0:GetCurrentMeasurement
XPP:R39:MPD:CH:0:GetTemperature
```
The low voltage has the additional rise/fall rates per channel:
```
XPP:R39:MPD:CH:0:SetVoltageRiseRate
XPP:R39:MPD:CH:0:SetVoltageFallRate
```
The high voltage has one voltage rise/fall for the whole card... so for all 8 channels, one rate governs the full set, and it has a different PV prefix, for example compare the channel 100 temperature with the module 10 voltage rise PV:
```
XPP:R39:MPD:CH:100:GetTemperature
XPP:R39:MPD:MOD:10:SetVoltageRiseRate
```

**Comment by cristinasewell** [comment]
Ohh thanks @ZLLentz - I need to adjust a few things then: 
Should I have `SetSwitch` as `print=True` and set all these with string?
```
XPP:R39:MPD:CH:0:SetSwitch Off
XPP:R39:MPD:CH:0:SetSwitch On
XPP:R39:MPD:CH:0:SetSwitch Emer
XPP:R39:MPD:CH:0:SetSwitch Reset
XPP:R39:MPD:CH:0:SetSwitch Clr
```
or should I use their corresponding values:
```
    Enums:            ( 5)
                      [ 0] Off
                      [ 1] On
                      [ 2] Reset
                      [ 3] EmerOff
                      [ 4] ClrEvnt
```
Just to make sure here, I'm going to have a few more common methods correct: `reset`, `emer_off` and `clear_event` (is emer - emergency) besides the `on` and `off`?

And for the `Low Voltage` I should have two functions probably:
`set_voltage_rise_rate` and `set_voltage_fall_rate` ?


Also, `:GetVoltage` is different than `:GetVoltageMeasurement` - what is the difference here? I am currently using this: https://github.com/pcdshub/pcdsdevices/blob/309285be459cf45258c2204bcc0420598669c5fb/pcdsdevices/mpod.py#L25-L27 for `voltage` - (based on this info https://github.com/pcdshub/Bug-Reports-and-Requests/issues/50#issuecomment-715477125) - is that fine? - or should I be using `:GetVoltage` for voltage and have `:GetVoltageMeasurement` into a different signal?

One more question though, am I on the right path with having the Class per Channel instead of a Class per HV module, and Class per LV module? (we can have modules with more channels, not only 8 correct?)

**Comment by ZLLentz** [comment]
Oh shoot some of my notes were mixed in with that... sorry! Only the PV names actually meant something, I was scribbling over a notepad with the button labels and copy/pasted the whole thing in.

Answering each line item:

- Yes I think `string=True` is best so that people can read off directly what state the MPOD is in. Your enums are correct, my noted scribbles are not.

- Regarding functions/methods, you only need to implement the ones Silke asked for, though I'm sure if you implemented all the variants for the `SetSwitch` PV they would get some use.

- I have absolutely no idea what the difference between the two get voltages are! I was simply harvesting a screen (and then I got distracted). You'll note in my screenshot they are always the same number, I suspect we can ignore the second one.

- I think having one class per channel is the best approach because different channels are typically used for very different things.

- One thing I meant to point out about the HV more closely is the differing prefix for the rise/fall rate... so that channel needs to be supplied two prefixes if we want any HV channel to able to configure the rise/fall rate

**Comment by cristinasewell** [comment]
That's great, thank you. 
Regarding this- to double check:
- ***One thing I meant to point out about the HV more closely is the differing prefix for the rise/fall rate... so that channel needs to be supplied two prefixes if we want any HV channel to able to configure the rise/fall rate***

I should be having something like this in the base `MPODChannel()` class:
```
  def __init__(self, prefix, prefix_ch,  name='MPOD', **kwargs):
```
And when we create an mpod channel object we'll have to always provide the prefix for the channel separately? 

hv_mpod = MPODChannelHV(prefix='XPP:R39:MPD:', prefix_ch='100')

something like this?

**Comment by silkenelson** [comment]
Actually, we tend to use GetVoltageMeasurement everywhere: the mpod has a 'Sense' which you read the GetVoltageMeasurement and one that gives you the voltage at the 'output'. We bind them together, which is why in practice it does not matter right now.

**Comment by cristinasewell** [comment]
> Actually, we tend to use GetVoltageMeasurement everywhere: the mpod has a 'Sense' which you read the GetVoltageMeasurement and one that gives you the voltage at the 'output'. We bind them together, which is why in practice it does not matter right now.

ok that sounds good, thank you @silkenelson - i'll keep using the `:GetVoltageMeasurement` for now then.

**Comment by ZLLentz** [comment]
Yes, that's the right idea with the doubling of the prefixes, but I think the channel prefix is the main one (since it's a channel object) and the mpod card prefix is the secondary one... I think I'd want to pass something like:
`HVChannel('XPP:R39:MPD:CH:100', card_prefix='XPP:R39:MPD:MOD:10', name='xpp_mpod_ch100')`

For consistency with the LV channels, and so we don't have many objects sharing the same main prefix.

I understand yours is shorter- I think it's important for clarity and simplicity of implementation for the main prefix to be the full channel prefix. Open to differing opinions of course.

**Comment by cristinasewell** [comment]
> Yes, that's the right idea with the doubling of the prefixes, but I think the channel prefix is the main one (since it's a channel object) and the mpod card prefix is the secondary one... I think I'd want to pass something like:
> `HVChannel('XPP:R39:MPD:CH:100', card_prefix='XPP:R39:MPD:MOD:10', name='xpp_mpod_ch100')`
> 
> For consistency with the LV channels, and so we don't have many objects sharing the same main prefix.
> 
> I understand yours is shorter- I think it's important for clarity and simplicity of implementation for the main prefix to be the full channel prefix. Open to differing opinions of course.

I see.., I was thinking a bit differently but your suggestion is much better. 
Please let me know if this is what you meant: 5bdc777

**Comment by ZLLentz** [comment]
Yeah, that seems pretty good. Straightforward and clear.

You didn't need to remove MPOD from all the classnames- I just couldn't remember what you had used and was trying to save time while writing my comment. I have no idea whether `MPODChannelLV` or `LVChannel` is preferable in any sense (in my head they are basically the same).

There's a small amount of code duplication here but it doesn't bother me much.

**Comment by silkenelson** [comment]
I'm leaning to leave MPOD in the name as we have other power supplies we support controls for.
I would think that we might want crate/card objects that are nested carte <- has cards <- have channels might be nice, but for questionnaire should create for refers to the single channels.

**Comment by cristinasewell** [comment]
> I'm leaning to leave MPOD in the name as we have other power supplies we support controls for.
> I would think that we might want crate/card objects that are nested carte <- has cards <- have channels might be nice, but for questionnaire should create for refers to the single channels.

Sounds good, i will add that back - thank you

**Comment by cristinasewell** [comment]
> Yeah, that seems pretty good. Straightforward and clear.
> 
> You didn't need to remove MPOD from all the classnames- I just couldn't remember what you had used and was trying to save time while writing my comment. I have no idea whether `MPODChannelLV` or `LVChannel` is preferable in any sense (in my head they are basically the same).
> 
> There's a small amount of code duplication here but it doesn't bother me much.

Ohh and I can totally put in the `MPODChannel` class at least the `set_voltage_rise_rate` and `set_voltage_fall_rate` functions so I don't duplicate them - i don't know if i can put anything else - thank you

**Comment by cristinasewell** [comment]
> > I'm leaning to leave MPOD in the name as we have other power supplies we support controls for.
> > I would think that we might want crate/card objects that are nested carte <- has cards <- have channels might be nice, but for questionnaire should create for refers to the single channels.
> 
> Sounds good, i will add that back - thank you

Any preferences though? 
```
MPODHVChannel
MPODHvChannel
MpodHvChannel
MPODChannelHV
```
or others - please let me know :)

**Comment by ZLLentz** [comment]
Appending to the end makes the classes sort together alphabetically, for whatever that's worth:
`MPODChannel`
`MPODChannelHV`
`MPODChannelLV`

**Review by ZLLentz — APPROVED** [review]
This looks ready to go to me, completes the linked issue cleanly and in full.

**Review by klauer — APPROVED** [review]
👍 merge at will

**Pull request merged**
